[project]
name = "eor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autogen-agentchat==0.2.40",
    "eventlet>=0.40.2",
    "flaml[automl]>=2.3.6",
    "gurobipy>=12.0.3",
    "pyautogen[blendsearch]<0.2",
    "pyomo>=6.9.3",
    "termcolor>=3.1.0",
]
